// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6JQwb1N_E2qOxi75sCDwnT45vuwGrA1s',
    appId: '1:308874007093:web:4073d89ad16d785119977c',
    messagingSenderId: '308874007093',
    projectId: 'yjk-flutter-firebase',
    authDomain: 'yjk-flutter-firebase.firebaseapp.com',
    storageBucket: 'yjk-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6qI5A7CfB7y07f3rsfg_Vb1mVUgpPgmM',
    appId: '1:308874007093:android:ea4720a68e2ac0e619977c',
    messagingSenderId: '308874007093',
    projectId: 'yjk-flutter-firebase',
    storageBucket: 'yjk-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0sjA5oTzSFrLaJc4snaW8TGhy3FkZ7DA',
    appId: '1:308874007093:ios:0edba6c09986648719977c',
    messagingSenderId: '308874007093',
    projectId: 'yjk-flutter-firebase',
    storageBucket: 'yjk-flutter-firebase.appspot.com',
    iosBundleId: 'com.example.firebase',
  );
}
